/* Run like regression.cjs. Verify hymn quick composition through the UI in isolated storage. */
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
(async () => {
  const browser = await chromium.launch({ headless: true,
    ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}) });
  try {
    const context = await browser.newContext({ viewport: { width: 320, height: 844 }, isMobile: true, hasTouch: true });
    const page = await context.newPage(), errors = [];
    page.on('pageerror', e => errors.push(e.message));
    await context.addInitScript(() => { window.rejections = []; window.addEventListener('unhandledrejection', e => window.rejections.push(String(e.reason))); });
    await page.route('http://songform.test/**', r => r.fulfill({ contentType: 'text/html', body: html }));
    await page.goto('http://songform.test/');
    await page.waitForFunction(() => state.loaded && !pendingSaves);
    const original = 'Intro-V1-Cx2(함께)-V2-C-inter(4마디)-Cx3-outro';
    await page.evaluate(async form => {
      const canvas = document.createElement('canvas'); canvas.width = 600; canvas.height = 840;
      const ctx = canvas.getContext('2d'); ctx.fillStyle = 'white'; ctx.fillRect(0, 0, 600, 840);
      const blob = await canvasToBlob(canvas);
      const song = { id: 'original', title: '선택 삭제 연습', key: 'G', tempo: 'mid', lastForm: form,
        labels: [], placement: { x: .5, y: .1, size: .025, page: 0 }, sheets: [{ blob, w: 600, h: 840 }] };
      await idbPut('songs', song);
      for (let i = 1; i <= 2; i++) await idbPut('weeks', { id: 'week' + i, date: '2026-10-0' + i,
        songs: [{ id: 'entry' + i, songId: song.id, form }], target: 20 });
    }, original);
    await page.reload();
    await page.waitForFunction(() => state.weeks.length === 2 && !pendingSaves);
    const open = () => page.evaluate(() => go({ name: 'song', songId: weekOf('week1').songs[0].songId, weekId: 'week1', entryId: 'entry1' }));
    await open();
    const initial = await page.evaluate(() => JSON.stringify({labels:state.edit.song.labels,placement:state.edit.song.placement,sheets:state.edit.song.sheets.map(s=>[s.w,s.h,s.blob.size])}));
    const click = action => page.locator(`[data-act=${action}]`).first().click();
    const verse = n => page.locator(`[data-hymn-verse="${n}"]`);
    const preview = () => page.locator('#hymnPreview').textContent();
    const current = () => page.evaluate(() => currentForm());
    const apply = async () => { await page.locator('#hymnApply').click(); await page.locator('#hymnApply').waitFor({state:'detached'}); };
    await click('hymnForm');
    assert.equal(await preview(), 'V1-V2-V3-V4');
    assert.equal(await verse(4).isChecked(), true);
    assert.equal(await current(), original);
    await page.locator('#hymnCancel').click(); assert.equal(await current(), original);
    assert.equal(await page.locator('[data-act=undoEdit]').isDisabled(), true);
    await click('hymnForm'); await apply();
    assert.equal(await current(), 'V1-V2-V3-V4');
    await click('undoEdit'); assert.equal(await current(), original);
    console.log('PASS four verses without unwanted chorus or bridge, cancellation and one-step undo');
    await click('hymnForm'); await verse(2).uncheck();
    await page.locator('[name=hymnChorus][value=each]').check();
    assert.equal(await preview(), 'V1-C-V3-C-V4-C');
    await page.locator('[name=hymnChorus][value=last]').check();
    assert.equal(await preview(), 'V1-V3-V4-C');
    await page.locator('#hymn-intro').check(); await page.locator('#hymn-inter').check(); await page.locator('#hymn-outro').check();
    assert.equal(await preview(), 'Intro-V1-inter-V3-inter-V4-C-outro');
    await page.locator('[name=hymnChorus][value=each]').check();
    const desired = 'Intro-V1-C-inter-V3-C-inter-V4-C-outro';
    assert.equal(await preview(), desired);
    assert.equal(await page.locator('.sheet').evaluate(el => el.scrollWidth <= el.clientWidth), true);
    assert.equal(await page.locator('.hymn-choice').first().evaluate(el => getComputedStyle(el).display), 'flex');
    for (const label of await page.locator('.hymn-choice').all()) assert.equal(await label.evaluate(el => el.scrollWidth <= el.clientWidth), true);
    const output = fs.mkdtempSync(path.join(os.tmpdir(), 'songform-hymn-'));
    await page.locator('.sheet').evaluate(el => el.scrollTop = 0);
    await page.locator('.toast.show').waitFor({state:'hidden'});
    await page.screenshot({ path: path.join(output, 'hymn-mobile.png'), animations: 'disabled' });
    await apply(); assert.equal(await current(), desired);
    const after = await page.evaluate(() => JSON.stringify({labels:state.edit.song.labels,placement:state.edit.song.placement,sheets:state.edit.song.sheets.map(s=>[s.w,s.h,s.blob.size])}));
    assert.equal(after, initial, 'only the form changes');
    await click('hymnForm'); assert.equal(await verse(2).isChecked(), false);
    assert.equal(await page.locator('[name=hymnChorus][value=each]').isChecked(), true);
    assert.equal(await preview(), desired);
    await page.locator('#hymnCancel').click();
    await click('undoEdit'); assert.equal(await current(), original);
    await click('redoEdit'); assert.equal(await current(), desired);
    console.log('PASS skipped verses, chorus placement, interludes, reopening and unchanged score annotations');
    await click('hymnForm'); await page.locator('#hymnAddVerse').click(); await page.locator('#hymnAddVerse').click();
    assert.equal(await verse(5).isChecked(), true); assert.equal(await verse(6).isChecked(), true);
    await page.locator('#hymnAllVerses').click(); await page.locator('#hymnAllVerses').click();
    assert.equal(await page.locator('#hymnApply').isDisabled(), true);
    assert.match(await preview(), /하나 이상/);
    await verse(6).check();
    assert.equal(await preview(), 'Intro-V6-C-outro');
    await apply(); assert.equal(await current(), 'Intro-V6-C-outro');
    await page.reload(); await page.waitForFunction(() => state.weeks.length === 2 && !pendingSaves); await open();
    assert.equal(await current(), 'Intro-V6-C-outro');
    await click('hymnForm');
    assert.equal(await verse(6).isChecked(), true); assert.equal(await verse(1).isChecked(), false);
    assert.equal(await preview(), 'Intro-V6-C-outro');
    await page.locator('#hymnCancel').click();
    const preserved = await page.evaluate(() => [songOf('original').lastForm, entryForm(weekOf('week2').songs[0])]);
    assert.deepEqual(preserved, [original, original]);
    await click('pdfWeek'); await page.locator('#pdfDownload[href]').waitFor();
    assert.doesNotMatch(await page.locator('.preview-check').first().textContent(), /송폼 없음/);
    await page.locator('#pvClose').click();
    await click('moreBlocks'); await page.locator('[data-act=addBlock][data-name=V4]').click();
    assert.equal(await current(), 'Intro-V6-C-outro-V4');
    await click('toggleLabel'); assert.equal(await page.locator('[data-act=labelText][data-t=V4]').count(), 1);
    console.log('PASS fifth/sixth verse, empty-selection guard, reload, PDF, manual V4 and isolation');
    assert.deepEqual(errors, []); assert.deepEqual(await page.evaluate(() => window.rejections), []);
    console.log('Artifacts:', output);
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
